feat: fail early if wiz can not auth

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -31,6 +31,11 @@ setupWiz() {
         --mount type=bind,src="$WIZ_DIR",dst=/cli \
         wiziocli.azurecr.io/wizcli:latest-amd64 \
         auth --id="$WIZ_API_ID" --secret "$WIZ_API_SECRET"
+    # check that wiz-auth work expected, and a file in WIZ_DIR is created
+    if [ -z "$(ls -A "$WIZ_DIR")" ]; then
+        echo "Wiz authentication failed, please confirm that credentials are set for WIZ_API_ID and WIZ_API_SECRET"
+        exit 1
+    fi
 }
 
 #$1 type, $2 name, $3 pass/fail, $4 result file
