feat: add Terraform Plan scan functionality, adding check to ensure  is specified

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -23,6 +23,11 @@ if [ "${SCAN_TYPE}" = "iac" ] && [[ -z "${BUILDKITE_PLUGIN_WIZ_PATH:-}" ]]; then
     exit 1
 fi
 
+if [ "${SCAN_TYPE}" = "terraform-plan" ] && [[ -z "${FILE_PATH}" ]]; then
+    echo "+++ 🚨 file-path must be specified to Terraform Plan file when scan-type is 'terraform-plan'"
+    exit 1
+fi
+
 api_secret_var="${BUILDKITE_PLUGIN_WIZ_API_SECRET_ENV:-WIZ_API_SECRET}"
 
 if [[ -z "${!api_secret_var:-}" ]]; then
@@ -152,8 +157,29 @@ terraformFilesScan() {
 }
 
 terraformPlanScan() {
-    # TODO: complete functionaility using Wiz CLI docker image
-    true
+    mkdir -p result
+    docker run \
+        --rm -it \
+        --mount type=bind,src="$WIZ_DIR",dst=/cli,readonly \
+        --mount type=bind,src="$PWD",dst=/scan \
+        wiziocli.azurecr.io/wizcli:latest-amd64 \
+        iac scan \
+        --name "$BUILDKITE_JOB_ID" -f human -o /scan/result/output,human \
+        --types 'Terraform' \
+        --path "/scan/$FILE_PATH"
+
+    exit_code="$?"
+    case $exit_code in
+    0)
+        buildAnnotation "Terraform Plan" "$BUILDKITE_LABEL" true "result/output" | buildkite-agent annotate --append --context 'ctx-wiz-iac-success' --style 'success'
+        ;;
+    *)
+        buildAnnotation "Terraform Plan" "$BUILDKITE_LABEL" false "result/output" | buildkite-agent annotate --append --context 'ctx-wiz-iac-warning' --style 'warning'
+        ;;
+    esac
+    # buildkite-agent artifact upload "result/**/*" --log-level info
+    # this post step will be used in template to check the step was run
+    echo "${BUILDKITE_BUILD_ID}" >check-file && buildkite-agent artifact upload check-file
 }
 
 case "${SCAN_TYPE}" in
